import { ledger, type Ledger } from '@shadowpoll/contract';
import { type ShadowPollProviders } from '@shadowpoll/api';
import { type ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { assertIsContractAddress } from '@midnight-ntwrk/midnight-js-utils';

/**
 * A helper that queries the current state of the data on the ledger, for a
 * specific ShadowPoll contract. The `Ledger` type returned here is not some
 * generic, abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration in the
 * ShadowPoll contract.
 */
export const getShadowPollLedgerState = async (
  providers: ShadowPollProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};
